### ISSUE TITLE
Not received email id in facebook

### ISSUE THREAD

**Issue by blpraveen** [destinomultimedia/ci_opauth#3]
I have not received email id information in the facebook response . what is the solution?

**Comment by mattiabasone** [comment]
Have you added "email" field in the request scope?
![screenshot 2014-08-12 12 44 02](https://cloud.githubusercontent.com/assets/3951536/3889397/083cbee6-220e-11e4-8755-dbf0d97c34e3.png)

**Comment by blpraveen** [comment]
Thanks. Solved
